# -*- coding: utf-8 -*-
"""pytorch_basic_using.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SmnUHwFzm2S5H_fS4ztEx8QXXeiZTZM0

#**Pytorch Tensor Basic Usage**<br>

*   create Tensor
*   Indexing, Joining, Slicing
*   Initializatiion
*   Math Operations

새 노트에서 런타임 > 런타임 유형 변경 > GPU 지정 <br>
새 노트마다 다시 지정해야 함
"""

# 1. Create Tensor
# 1) random numbers
import torch

# torch.rand(sizes) => 0 ~ 1 사이의 값으로 랜덤값 발생함
# sizes : 1차원 갯수 | 2차원 행렬 갯수 지정
# 0과 1사이의 실수형 숫자를 균등하게 생성
x = torch.rand(2,3) # 2행 3열로 탠서를  생성하고, 랜덤값으로 채움

x
print(x)

# 2. torch.randn(sizes)
# 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해서 랜덤값 생성
x = torch.randn(2, 3)
x

# 3. torch.randperm(n) => permutation of 0~ n
x = torch.randperm(5)
x

"""랜덤값을 가지는 텐서 생성 함수들 <br>
1. torch.rand()         :  0 과 1 사이의 숫자를 균등하게 생성<br>
2. torch.rand_like()    : 사이즈를 튜플로 입력하지 않고 기존의 텐서와 동일한 텐서 만들 때 사용<br>
3. torch.randn()        : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 생성<br>
4. torch.rand_like()    : 사이즈를 튜플로 입력하지 않고 기존의 텐서를 정의함<br>
5. torch.randint()      : 주어진 범위 내의 정수를 균등하게 생성, 자료형은 torch.float32 <br>
6. torch.randint_like() : 기존의 텐서를 정의함<br>
7. torch.randperm()     : 주어진 범위 내의 정수를 랜덤하게 생성 <br>

"""

# 2) zeros, ones, arange

# torch.zeros(2, 3) => [[0,0,0],[0,0,0]]
x = torch.zeros(2,3)
x # float32

# torch.ones(2, 3)
x = torch.ones(2,3)
x

# torch.arange(start, end, step)
x = torch.arange(0, 3, step=0.5)
x

"""# 3. Tensor Data Type

"""

# torch.floatTensor(size or list)
x = torch.FloatTensor(2, 3)
x

x = torch.FloatTensor([12, 35])
x

# torch.type_as(tensor_type)
# 기존의 텐서의 값의 자료형을 바꿀 때 사용
x = x.type_as(torch.IntTensor())
x

"""# 4. Numpy to Tensor, Tensor to Numpy"""

import numpy as np

# torch.from_numpy(ndarray) => tensor
x1 = np.ndarray(shape=(2, 3), dtype = int, buffer=np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)
x2

# torch.numpy() -> ndarray
x3 = x2.numpy()
x3

"""# 5. Tensor on CPU & GPU

"""

x = torch.FloatTensor(([1, 2, 3], [4, 5, 6]))
x

x_gpu = x.cuda()
x_gpu

x_cpu = x_gpu.cpu()
x_cpu

"""# 6. Tensor Size"""

# tensor.size() => 인덱스 값
x = torch.FloatTensor(10, 12, 3, 3)
x.size()[:]
print(x, x.size()[:])

"""# 2. Indexing, Slicing, Joining
#1) Indexing
"""

# torch.index_select(input, dim, index)
# input : 대상 텐서
# dim : 선택할 차원의 인덱스를 지정, 0은 첫번째 차원(행을 의미), 1은 두번째 차원(열을 의미)을 의미함
# index : 선택할 인덱스를 포함한 1차원 텐서를 정의함, [0,3]은 0번째와 3번째를 의미함
x = torch.rand(4, 3)
out = torch.index_select(x, 0, torch.LongTensor([0, 3])) # x 텐서에서 0행과 3행 추출
print( x, '\n', out )

# 파이썬 indexing 사용 가능
x[:, 0], x[0, :], x[0:2, 0:2]

# torch.masked_select(input, mask)
x = torch.randn(2,3)
mask = torch.BoolTensor([[False, False, True], [False, True, False]])
out= torch.masked_select(x, mask)
x, mask, out

"""# 2) Joining"""

# torch.cat(seq, dim=0)
x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])

z1 = torch.cat([x,y], dim=0) # dim=0 (행방향) : 아래로 합침
z2 = torch.cat([x,y], dim=1) # dim=1 (열방향) : 오른쪽에 합쳐짐

x, y, z1, z2

# torch.stack(sequences, dim=0) => 새로운 차원으로 추가
x = torch.FloatTensor([[1,2,3],[4,5,6]]) # shape : (2, 3)
x_stack = torch.stack([x,x,x,x], dim=0) # shape : (4, 2, 3)
x_stack

"""# 3) Slicing"""

# torch.chunk(tensor, chunks, dim=0)
x_1, x_2 = torch.chunk(z1, 2, dim=0) # dim=0 : 행들을 2개로 분할
y_1, y_2, y_3 = torch.chunk(z1, 3 , dim=1) # dim=1 : 열들을 3개로 분할

z1, x_1, x_2, y_1, y_2, y_3

# torch.split(tensor, split_size, dim=0)
x1, x2 = torch.split(z1, 2, dim=0) # 행으로 2개 분리
y1 = torch.split(z1, 2, dim=1) # 3개의 열을 2개로 분리

z1, x1, x2, y1

"""# 4) squeezing

"""

# torch.squeeze(input, dim=None) => 숫자가 1 인 차원을 제거
x1 = torch.FloatTensor(10, 1, 3, 4)
# 차원(dimension)의 개념
# 10 : batch size (데이터 한 묶음당 들어있는 데이터(x,y)쌍 갯수)
# 1 : channel size (색상 채널 1은 그레이톤 흑백이미지를 의미함)
# 3 : width image size
# 4 : height image size

x2 = torch.squeeze(x1)

x1, x2, x1.size(), x2.size()

# torch.unsqueeze(input, dim=None) => 숫자가 1인 차원을 추가
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.unsqueeze(x1, dim=0) # dim=0 면 첫번째 도메인 위치에 추가

x1, x2, x1.size(), x2.size()

"""# 3. Initialization"""

import torch.nn.init as init

x1 = init.uniform(torch.FloatTensor(3, 4), a=0, b=9) # a와 b 사이의 값으로 초기화
x2 = init.normal(torch.FloatTensor(3, 4), std=0.2) # 표준편차 0.2를 적용해서 초기화
x3 = init.constant(torch.FloatTensor(3, 4), 3.1415926535) # 지정된 상수값으로 초기화

x1, x2, x3

"""# 4. Math Operation
# 1. Arithmetic Operations
"""

# torch.add() : 더하기 (백터연산 개념)
x1 = torch.FloatTensor([[1,2,3], [4,5,6]])
x2 = torch.FloatTensor([[1,2,3], [4,5,6]])
add = torch.add(x1, x2)

x1, x2, add, x1+x2, x1-x2

# torch.add() broadcasting (숫자와의 연산)
x2 = torch.add(x1, 10)

x1, x2, x1 + 10, x2 - 10

# torch.mul() : 곱하기
x1 = torch.FloatTensor([[1,2,3], [4,5,6]])
x2 = torch.FloatTensor([[1,2,3], [4,5,6]])
mul = torch.mul(x1, x2)

x1, x2, mul, x1*x2

# torch.mul() broadcasting (숫자와의 연산)
mul2 = torch.mul(x1, 10)
mul2, x1 * 10, mul2 == x1*10

# torch.div() : 나누기 (몫)
div = torch.div(x1, 5)

div, x1 / 5, div == x1/5

"""# 2) Other Math Operations"""

# torch.pow(input, exponent)
x1 = torch.FloatTensor(3, 4)

x1, torch.pow(x1, 2), x1 ** 2

# torch.exp(tensor, out=None) : 지수함수
x1 = torch.FloatTensor(3, 4)
out = torch.exp(x1)

x1, out

# torch.log(input, *, out=None)
out = torch.log(x1)

x1, out

"""# 3) Matrix Operations"""

# torch.mm(mat1, mat2) => matrix multiplication (행렬곱)
x1 = torch.FloatTensor(3, 4)
x2 = torch.FloatTensor(4, 5)
out = torch.mm(x1, x2)

x1, x2, out

# torch.bmm(batch1, batch2) => batch에 대한 행렬곱 연산
# 맨 앞의 batch 는 차원을 유지하면서 뒤 요소들의 행렬곱 연산 수행함

x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.FloatTensor(10, 4, 5)
out = torch.bmm(x1, x2)

out.size()

# torch.dot(tensor1, tensor2)
x1 = torch.FloatTensor([1,2,3,4])
x2 = torch.FloatTensor([2,3,4,5])

torch.dot(x1, x2)
# 2+3+4+5 + 4+6+8+10 + 6+9+12+15 + 8+12+16+20

# torch.t(matrix) : 텐서의 전치 연산 (행과열을 바꾸는 연산)
x1 = torch.FloatTensor(3, 4)

x1, x1.t(), torch.t(x1)

# torch.transpose(input, dim_0, dim_1)
# 바꿀 차원을 2개 지정함 => 텐서 내부 차원끼리 바꾸기함
x1 = torch.FloatTensor(10, 3, 4)

# 1차원과 2차원을 서로 바꿈
x1.size(), torch.transpose(x1, 1, 2).size(), x1.transpose(1, 2).size()

# torch.eig(input, eigenvectors=False)
# 고유값 (eigen_value), 고유백터(eigen_vector) 로 변환하는 함수
x1 = torch.FloatTensor(4, 4)

# 고유값과 고유백터 계산
x1, torch.linalg.eig(x1)
# 고유값과 고유백터 :
# 어떤 변환(행렬)을 적용했을 때 방향은 변하지 않고 크기만 변하는 특별한 백터와 변화량을 의미함

# 백터(Vector) : 크기 + 방향을 가진 값임
# 예 : (2, 3) 백터는 오른쪽 2, 위쪽 3 방향을 가짐

# 행렬(Matrix) : 백터를 변형시키는 도구
# 예 : 회전, 확대, 축소, 뒤집기 등을 수행
# 예 : [1,0] => [2,0] 크기가 2배 => 고유값은 2임 (고유백터가 얼마나 확대/축소되었는지 나타내는 값)