# -*- coding: utf-8 -*-
"""Regression_and_Classification_Model_Hands-on.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Hw8Eu3sufAcxoiFOHrP8rCG2ObWobt9

0. 라이브러리 불러오기
"""

# PyTorch 핵심 라이브러리
import torch

# 신경망 모델을 만들기 위한 모듈
import torch.nn as nn

# 최적화 알고리즘을 사용하기 위한 모듈
import torch.optim as optim

# 데이터셋 분리, 평가 지표 사용
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, classification_report

# 데이터 전처리용
from sklearn.preprocessing import StandardScaler, LabelEncoder

# 실습용 데이터셋
import seaborn as sns

# 데이터 처리
import pandas as pd
import numpy as np

# 시각화
import matplotlib.pyplot as plt

# 실행 장치 설정
# GPU가 있으면 cuda, 없으면 cpu 사용
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("사용 장치:", device)

"""1. pythorch 회귀모델 실습 <br>
데이터셋 : tips<br>

"""

