# -*- coding: utf-8 -*-
"""ML_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LyJ9mn0s0vb5v39D52ihebQVDorJg0I

# [실습문제] ======================================================
Wine 데이터셋을 이용한 PyTorch 다중 분류 모델 만들기<br>
    Wine 데이터셋은 와인의 화학 성분을 이용하여 와인 종류를 분류하는 데이터입니다.

* 실습문제 1. Wine 데이터셋 불러오기<br>
    sklearn.datasets의 load_wine()을 사용하여 데이터를 불러오시오.
"""

from sklearn.datasets import load_wine
import pandas as pd

wine = load_wine()

X = wine.data
y = wine.target

feature_names = wine.feature_names
target_names = wine.target_names

df = pd.DataFrame(X, columns=feature_names)
df["target"] = y
df["target_name"] = df["target"].apply(lambda x: target_names[x])

print("입력 데이터 크기:", X.shape)
print("정답 데이터 크기:", y.shape)
print("특성 이름:", feature_names)
print("분류 클래스:", target_names)

df.head()

"""* 실습문제 2. 데이터 기본 정보 확인하기<br>
    Wine 데이터셋의 크기, 기초 통계량, 클래스별 개수를 확인하시오.   
"""

print("데이터 크기:", df.shape)

print("\n기초 통계량:")
print(df.describe())

print("\n클래스별 개수:")
print(df["target_name"].value_counts())

"""* 실습문제 3. 데이터 시각화하기<br>
    와인 클래스별 데이터 개수를 그래프로 출력하시오.  
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(data=df, x="target_name")
plt.title("Wine 클래스별 데이터 개수")
plt.xlabel("Wine Class")
plt.ylabel("Count")
plt.show()

"""* 실습문제 4. 입력 데이터와 정답 데이터 분리하기<br>
    입력 데이터 X와 정답 데이터 y를 분리하시오.
"""

X = df[feature_names].values
y = df["target"].values

print("입력 데이터 크기:", X.shape)
print("정답 데이터 크기:", y.shape)

"""* 실습문제 5. 학습용 / 테스트용 데이터 분리하기<br>
    전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분리하시오.
"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("학습용 입력 데이터:", X_train.shape)
print("테스트용 입력 데이터:", X_test.shape)
print("학습용 정답 데이터:", y_train.shape)
print("테스트용 정답 데이터:", y_test.shape)

"""* 실습문제 6. 데이터 표준화하기<br>
    StandardScaler를 사용하여 학습 데이터와 테스트 데이터를 표준화하시오.
"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("표준화 전 데이터:")
print(X_train[0])

print("\n표준화 후 데이터:")
print(X_train_scaled[0])