# -*- coding: utf-8 -*-
"""ML_practice2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvKScz7HMeSJGvScE-dp6U6QgNOTihxJ
"""

# ============================================================
#  라이브러리 불러오기
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
import torch.optim as optim

from torch.utils.data import TensorDataset, DataLoader

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ============================================================
# 실행 장치 설정하기
# ============================================================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("사용 장치:", device)

if device.type == "cuda":
    print("GPU 이름:", torch.cuda.get_device_name(0))

# ============================================================
# 실습문제 1. Breast Cancer 데이터셋 불러오기
# ============================================================

cancer = load_breast_cancer()

X = cancer.data
y = cancer.target

feature_names = cancer.feature_names
target_names = cancer.target_names

print("입력 데이터 크기:", X.shape)
print("정답 데이터 크기:", y.shape)
print("특성 개수:", len(feature_names))
print("클래스 이름:", target_names)

# ============================================================
# DataFrame으로 변환하기
# ============================================================

df = pd.DataFrame(X, columns=feature_names)

df["target"] = y

df["target_name"] = df["target"].apply(lambda x: target_names[x])

df.head()

# ============================================================
# 실습문제 2. 데이터 기본 정보 확인하기
# ============================================================

print("데이터 크기:", df.shape)

print("\n기초 통계량:")
print(df.describe())

print("\n클래스별 데이터 개수:")
print(df["target_name"].value_counts())

print("\n결측치 확인:")
print(df.isnull().sum())

# ============================================================
# 실습문제 3. 클래스 분포 시각화하기
# ============================================================

sns.countplot(data=df, x="target_name")
plt.title("Breast Cancer Class Count")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()

# ============================================================
# 상관관계 시각화하기
# ============================================================

plt.figure(figsize=(14, 10))

corr = df[feature_names].corr()

sns.heatmap(
    corr,
    cmap="coolwarm",
    annot=False
)

plt.title("Breast Cancer Feature Correlation Heatmap")
plt.show()

# ============================================================
# 실습문제 4. 입력 데이터와 정답 데이터 분리하기
# ============================================================

X = df[feature_names].values
y = df["target"].values

print("입력 데이터 X 크기:", X.shape)
print("정답 데이터 y 크기:", y.shape)

# ============================================================
# 실습문제 5. 학습용 / 테스트용 데이터 분리하기
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("학습용 입력 데이터:", X_train.shape)
print("테스트용 입력 데이터:", X_test.shape)
print("학습용 정답 데이터:", y_train.shape)
print("테스트용 정답 데이터:", y_test.shape)

# ============================================================
# 실습문제 6. 데이터 표준화하기
# ============================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

print("표준화 전 첫 번째 데이터:")
print(X_train[0])

print("\n표준화 후 첫 번째 데이터:")
print(X_train_scaled[0])