# -*- coding: utf-8 -*-
"""test2-breast_cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fT_DENx1vv4L5jgjy_FldqhlBiupjTsV

[위의 실습 1 ~ 6번까지를 다음 데이터셋을 사용하여 torch 로 구현해 보시오] ========================
  Breast Cancer 데이터셋

특징
유방암 양성/악성 분류
의료 AI 실습에 자주 사용
이진 분류(Binary Classification)

사용 코드
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()
"""

# ============================================================
# 1. 기본 라이브러리 불러오기
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# PyTorch 핵심 라이브러리
import torch

# 신경망 모델을 만들기 위한 모듈
import torch.nn as nn

# 최적화 알고리즘을 사용하기 위한 모듈
import torch.optim as optim

# PyTorch Dataset, DataLoader 사용
from torch.utils.data import TensorDataset, DataLoader

# Iris 데이터셋
# from sklearn.datasets import load_iris
# from sklearn.datasets import load_wine
from sklearn.datasets import load_breast_cancer

# 학습용 / 테스트용 데이터 분리
from sklearn.model_selection import train_test_split

# 데이터 표준화
from sklearn.preprocessing import StandardScaler

# 평가 지표
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ============================================================
# 2. 실행 장치 설정 - GPU 사용 가능 여부 확인
# ============================================================

# Colab에서 GPU를 켜면 cuda 사용 가능
# GPU가 없으면 CPU 사용
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("사용 장치:", device)

cancer = load_breast_cancer()

# 입력 데이터
X = cancer.data

# 정답 데이터
y = cancer.target

feature_names = cancer.feature_names
target_names = cancer.target_names

df = pd.DataFrame(X, columns=feature_names)
df['target'] = y
df['target_name'] = df['target'].apply(lambda x : target_names[x])

df.head()
# df.tail()

print("데이터 크기:", df.shape)
print('---------------------------')

print("\n기초 통계량:")
print(df.describe())
print('---------------------------')

print("\n클레스별 개수:")
print(df["target_name"].value_counts())
print('---------------------------')

sns.countplot(data=df, x="target_name")
plt.title("cancer 데이터 개수")
plt.xlabel("클래스")
plt.ylabel("개수")
plt.show()

sns.pairplot(df, hue="target_name")
plt.show()

X = df[feature_names].values
y = df["target"].values

print("입력 데이터 크기:", X.shape)
print("정답 데이터 크기:", y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("학습용 입력 데이터:", X_train.shape)
print("테스트용 입력 데이터:", X_test.shape)

scaler = StandardScaler()

# 학습 데이터 기준으로 평균과 표준편차 계산 후 변환
X_train_scaled = scaler.fit_transform(X_train)

# 테스트 데이터는 학습 데이터 기준으로만 변환
X_test_scaled = scaler.transform(X_test)


print("표준화 전 데이터:")
print(X_train[0])

print("\n표준화 후 데이터:")
print(X_train_scaled[0])

# 입력 데이터는 float32 타입으로 변환
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)

# 정답 데이터는 CrossEntropyLoss 사용을 위해 long 타입으로 변환
y_train_tensor = torch.tensor(y_train, dtype=torch.long)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

print(X_train_tensor.shape)
print(y_train_tensor.shape)