# -*- coding: utf-8 -*-
"""test1_wine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YEHshHLUuQS6Wp-iuHOLjMfP_U8MkujF

[실습문제] ======================================================
Wine 데이터셋을 이용한 PyTorch 다중 분류 모델 만들기
    Wine 데이터셋은 와인의 화학 성분을 이용하여 와인 종류를 분류하는 데이터입니다.

실습문제 1. Wine 데이터셋 불러오기
  sklearn.datasets의 load_wine()을 사용하여 데이터를 불러오시오.

실습문제 2. 데이터 기본 정보 확인하기
  Wine 데이터셋의 크기, 기초 통계량, 클래스별 개수를 확인하시오.

실습문제 3. 데이터 시각화하기
  와인 클래스별 데이터 개수를 그래프로 출력하시오.

실습문제 4. 입력 데이터와 정답 데이터 분리하기
  입력 데이터 X와 정답 데이터 y를 분리하시오.

실습문제 5. 학습용 / 테스트용 데이터 분리하기
  전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분리하시오.

실습문제 6. 데이터 표준화하기
  StandardScaler를 사용하여 학습 데이터와 테스트 데이터를 표준화하시오.

임포트
"""

# ============================================================
# 1. 기본 라이브러리 불러오기
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# PyTorch 핵심 라이브러리
import torch

# 신경망 모델을 만들기 위한 모듈
import torch.nn as nn

# 최적화 알고리즘을 사용하기 위한 모듈
import torch.optim as optim

# PyTorch Dataset, DataLoader 사용
from torch.utils.data import TensorDataset, DataLoader

# Iris 데이터셋
# from sklearn.datasets import load_iris
from sklearn.datasets import load_wine

# 학습용 / 테스트용 데이터 분리
from sklearn.model_selection import train_test_split

# 데이터 표준화
from sklearn.preprocessing import StandardScaler

# 평가 지표
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ============================================================
# 2. 실행 장치 설정 - GPU 사용 가능 여부 확인
# ============================================================

# Colab에서 GPU를 켜면 cuda 사용 가능
# GPU가 없으면 CPU 사용
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("사용 장치:", device)

"""실습문제 1. Wine 데이터셋 불러오기
  sklearn.datasets의 load_wine()을 사용하여 데이터를 불러오시오.
"""

wine = load_wine()

# 입력 데이터
X = wine.data

# 정답 데이터
y = wine.target

feature_names = wine.feature_names
target_names = wine.target_names

df = pd.DataFrame(X, columns=feature_names)
df["target"] = y
df["target_name"] = df["target"].apply(lambda x: target_names[x])

df.head()

"""실습문제 2. 데이터 기본 정보 확인하기
  Wine 데이터셋의 크기, 기초 통계량, 클래스별 개수를 확인하시오.
"""

print("데이터 크기:", df.shape)
print('---------------------------')

print("\n기초 통계량:")
print(df.describe())
print('---------------------------')

print("\n클레스별 개수:")
print(df["target_name"].value_counts())
print('---------------------------')

"""실습문제 3. 데이터 시각화하기
  와인 클래스별 데이터 개수를 그래프로 출력하시오.

"""

sns.countplot(data=df, x="target_name")
plt.title("wine 데이터 개수")
plt.xlabel("클래스")
plt.ylabel("개수")
plt.show()

sns.pairplot(df, hue="target_name")
plt.show()

"""실습문제 4. 입력 데이터와 정답 데이터 분리하기
  입력 데이터 X와 정답 데이터 y를 분리하시오.
"""

X = df[feature_names].values
y = df["target"].values

print("입력 데이터 크기:", X.shape)
print("정답 데이터 크기:", y.shape)

"""실습문제 5. 학습용 / 테스트용 데이터 분리하기
  전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분리하시오.\

"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("학습용 입력 데이터:", X_train.shape)
print("테스트용 입력 데이터:", X_test.shape)

"""실습문제 6. 데이터 표준화하기
  StandardScaler를 사용하여 학습 데이터와 테스트 데이터를 표준화하시오.
"""

scaler = StandardScaler()

# 학습 데이터 기준으로 평균과 표준편차 계산 후 변환
X_train_scaled = scaler.fit_transform(X_train)

# 테스트 데이터는 학습 데이터 기준으로만 변환
X_test_scaled = scaler.transform(X_test)